trigger:
- master
pr:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure/build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: azure/build.yml

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: azure/build.yml